#!/usr/bin/env python3
"""Assemble the self-contained Luau picker test script.

Reads the committed dataset (../assets/emoji.json) and ../picker.luau, and
writes one script:

    local DATASET = { …dataset as a Luau table… }
    local PICKER_SRC = [====[ …verbatim picker.luau… ]====]
    …harness.luau verbatim…

so the stock `luau` CLI can run the search/ranking/interaction tests with
zero host dependencies and zero file IO. Run from the tests directory:

    python3 build_test.py --out <test.luau>
"""

import argparse
import json
from pathlib import Path

DELIM = "===="


def luau_string(s: str) -> str:
    if "]" + DELIM + "]" in s:
        raise ValueError(f"string contains the long-bracket delimiter: {s!r}")
    return f"[{DELIM}[{s}]{DELIM}]"


def luau_entry(entry: dict) -> str:
    parts = [f"e={luau_string(entry['e'])}", f"n={luau_string(entry['n'])}",
             f"l={luau_string(entry['l'])}",
             f"c={luau_string(entry['c'])}"]
    if "a" in entry:
        parts.append("a={" + ",".join(luau_string(a) for a in entry["a"]) + "}")
    parts.append("k={" + ",".join(luau_string(k) for k in entry["k"]) + "}")
    if entry.get("s") == 1:
        parts.append("s=1")
    return "{" + ",".join(parts) + "}"


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--dataset", default=str(Path(__file__).parent.parent / "assets" / "emoji.json"))
    ap.add_argument("--picker", default=str(Path(__file__).parent.parent / "picker.luau"))
    ap.add_argument("--out", required=True)
    args = ap.parse_args()

    dataset = json.loads(Path(args.dataset).read_text(encoding="utf-8"))
    picker_src = Path(args.picker).read_text(encoding="utf-8")
    harness = (Path(__file__).parent / "harness.luau").read_text(encoding="utf-8")

    out = ["-- Generated by build_test.py — do not edit.\n"]
    out.append("local DATASET = {\n")
    out.append(",\n".join(luau_entry(e) for e in dataset))
    out.append("\n}\n")
    out.append(f"local PICKER_SRC = {luau_string(picker_src)}\n")
    out.append(harness)

    Path(args.out).write_text("".join(out), encoding="utf-8")
    print(f"{args.out}: {len(dataset)} entries")


if __name__ == "__main__":
    main()
