-- Generated by HyprMod

-- Settings
hl.config({
    cursor = {
        enable_hyprcursor = false,
        no_hardware_cursors = 1,
    },
    input = {
        accel_profile = "flat",
        sensitivity = 0.05,
    },
})
