color0 #424848
color1 #ffb4ab
color2 #b9cacc
color3 #c2c7c8
color4 #cdc3d4
color5 #b9cacc
color6 #c2c7c8
color7 #e4e2e2
color8 #8c9292
color9 #ffb4ab
color10 #b9cacc
color11 #c2c7c8
color12 #cdc3d4
color13 #b9cacc
color14 #c2c7c8
color15 #e4e2e2

cursor                #e4e2e2
cursor_text_color     #000000
background            #000000
foreground            #e4e2e2
selection_foreground  #c2c7c8
selection_background  #424848
active_border_color   #b9cacc
inactive_border_color #353b3b
url_color             #b9cacc

active_tab_foreground   #243335
active_tab_background   #b9cacc
inactive_tab_foreground #c2c7c8
inactive_tab_background #353b3b
cursor_trail_color      #c2c7c8
